---
version: "3.5"
services:
  node:
    build:
      args:
        FXNET: mainnet
      context: ..
      network: host
    command: /opt/scripts/entrypoint.sh
    container_name: fxcore-mainnnet
    entrypoint: bash
    environment:
      - FXHOME=/home/fxcore/.fxcore
      - FXNET=mainnet
      - FXSNAPURL=https://fx-testnet.s3.amazonaws.com/fxcore-snapshot-testnet-2021-11-22.tar.gz
      - HOME=/home/fxcore
    image: fxcore:mainnet
    networks:
      fx-net:
        ipv4_address: 10.10.0.2
    logging:
      driver: syslog
    ports:
      - 1317:1317  # REST API
      - 26656:26656  # P2P
      - 26657:26657  # RPC
      - 26660:26660  # ABCI
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 65535
    volumes:
      - fxcore-mainnet-config:/home/fxcore/.fxcore/config:rw
      - fxcore-mainnet-data:/home/fxcore/.fxcore/data:rw
      - ../scripts:/opt/scripts:ro
networks:
  fx-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
volumes:
  fxcore-mainnet-config:
    external: true
  fxcore-mainnet-data:
    external: true
