---
version: "3.5"
services:
  node:
    build:
      args:
        FXNET: testnet
      context: ..
      network: host
    command: /opt/scripts/entrypoint.sh
    container_name: fxcore-testnet
    entrypoint: bash
    environment:
      - FXHOME=/home/fxcore/.fxcore
      - FXNET=testnet
      - HOME=/home/fxcore
    image: fxcore:testnet
    logging:
      driver: syslog
    ports:
      - 1317:1317  # REST API
      - 26656:26656  # P2P
      - 26657:26657  # RPC
      - 26660:26660  # ABCI
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 65535
    volumes:
      - fxcore-testnet-config:/home/fxcore/.fxcore/config:rw
      - fxcore-testnet-data:/home/fxcore/.fxcore/data:rw
      - ../scripts:/opt/scripts:ro
volumes:
  fxcore-testnet-config:
    external: true
  fxcore-testnet-data:
    external: true
