---
version: "3.5"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ../monitoring/grafana/config.env
    restart: always
    networks:
      fxnet-testnet:
        ipv4_address: 10.10.10.4
  node:
    build:
      args:
        FXNET: testnet
      context: ..
      network: host
    command: /opt/scripts/entrypoint.sh
    container_name: fxcore-testnet
    entrypoint: bash
    environment:
      - FXHOME=/home/fxcore/.fxcore
      - FXNET=testnet
      - FXSNAPURL=https://fx-testnet.s3.amazonaws.com/fxcore-snapshot-testnet-2022-06-20.tar.gz
      - HOME=/home/fxcore
    image: fxcore:testnet
    networks:
      fxnet-testnet:
        ipv4_address: 10.10.10.2
    ports:
      - 1317:1317  # REST API
      - 8545:8545  # EVM
      - 26656:26656  # P2P
      - 26657:26657  # RPC
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 65535
    volumes:
      - fxcore-testnet-config:/home/fxcore/.fxcore/config:rw
      - fxcore-testnet-data:/home/fxcore/.fxcore/data:rw
      - ../scripts:/opt/scripts:ro
  prometheus:
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web-config.yml'
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    networks:
      fxnet-testnet:
        ipv4_address: 10.10.10.3
    volumes:
      - ../monitoring/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
networks:
  fxnet-testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
volumes:
  alertmanager_data:
  alertmanagerbot_data:
  fxcore-testnet-config:
    external: true
  fxcore-testnet-data:
    external: true
  grafana_data:
  prometheus_data:
