---
version: "3"
services:
  init:
    build: ..
    container_name: fxcore-testnet-init
    command: /opt/scripts-init/init.sh
    entrypoint: bash
    environment:
      - FXHOME=/home/fxcore/.fxcore
      - HOME=/home/fxcore
    image: fxcore:testnet
    volumes:
      - ./scripts-init:/opt/scripts-init
      - fxcore-testnet-config:/home/fxcore/.fxcore/config:rw
      - fxcore-testnet-data:/home/fxcore/.fxcore/data:rw
  node:
    build: ..
    command: ["start"]
    container_name: fxcore-testnet
    depends_on:
      - init
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      - FXHOME=/home/fxcore/.fxcore
      - HOME=/home/fxcore
    image: fxcore:testnet
    logging:
      driver: syslog
    ports:
      - 1317:1317  # REST API
      - 26656:26656  # P2P
      - 26657:26657  # RPC
      - 26660:26660  # ABCI
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 65535
    volumes:
      - fxcore-testnet-config:/home/fxcore/.fxcore/config:rw
      - fxcore-testnet-data:/home/fxcore/.fxcore/data:rw
volumes:
  fxcore-testnet-config:
    external: true
  fxcore-testnet-data:
    external: true
