---
name: Docker Test

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-fx-test.yml'
  push:
    branches:
      - "master"
      - "dev*"
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-fx-test.yml'

jobs:
  Hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: Dockerfile
  Docker-FX:
    needs: Hadolint
    container:
      image: functionx/fx-core:${{ matrix.tag }}
    runs-on: ubuntu-latest
    steps:
      - run: fxcored network
      - run: fxcored init fx-zakir
    strategy:
      matrix:
        tag:
          - dhobyghaut-1.1
          - mainnet-1.0
          - testnet-1.0
  Docker:
    runs-on: ubuntu-latest
    needs: Hadolint
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build --build-arg FXNET=${{ matrix.net }} --tag fxcore .
      - name: Create config and data dirs
        run: mkdir -m=777 -v config data
      - name: Run init
        run: >-
          docker run
          -v "$PWD"/config:/home/fxcore/.fxcore/config:rw
          -v "$PWD"/data:/home/fxcore/.fxcore/data:rw
          fxcore init fx-zakir --overwrite
    strategy:
      matrix:
        net:
          - mainnet
          - testnet
