---
name: Docker Testnet

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**/Dockerfile'
      - '.github/workflows/docker-testnet.yml'
  push:
    branches:
      - "master"
      - "dev*"
    paths:
      - '**/Dockerfile'
      - '.github/workflows/docker-testnet.yml'

jobs:
  Hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: testnet/Dockerfile
  Docker-FX:
    runs-on: ubuntu-latest
    needs: Hadolint
    container:
      image: functionx/fx-core:testnet-1.0
    steps:
      - run: fxcored init fx-zakir
  Docker-Testnet:
    runs-on: ubuntu-latest
    needs: Hadolint
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build --tag fxcore testnet
      - name: Run
        run: docker run fxcore init fx-zakir -o
